### ISSUE TITLE
Report is Created But Won't Load in Firefox or Chrome or Other Browser - Spinner Spins

### ISSUE THREAD

**Issue by rmmcclay** [allinurl/goaccess#1694]
Successfully compiled and installed goaccess.  It runs successfully and creates "report.html". The file is about 4K, but it won't load.  Just an endless spinner. Any ideas? 

Also, the command line generates the reports perfectly on the console.

**Comment by MrSorcus** [comment]
What `Console` tab says in an Inspect Code mode?

**Comment by rmmcclay** [comment]
Nothing. No errors, no warnings.

**Comment by MrSorcus** [comment]
Can you provide a link?

**Comment by rmmcclay** [comment]
Yes, though it is temporary: 
http://pqcstudio.com/report.html

**Comment by MrSorcus** [comment]
@rmmcclay your `report.html` doesn't contain 2 last js scripts.
If you open it, you will see 2 empty `<script></script>`.
And if use paste manually missed code from https://rt.goaccess.io/ (for example) you've got it work.
But why it happen i don't know.
What version you use? 1.3 release or `master` branch?

**Comment by MrSorcus** [comment]
@rmmcclay i found a similar issue, that might help you - https://github.com/allinurl/goaccess/issues/1415

**Comment by allinurl** [comment]
@MrSorcus Thanks for posting that. @rmmcclay Please try building from [**development**](https://github.com/allinurl/goaccess#build-from-github-development) as I believe this has been fixed upstream. Let me know if that solves the issue. Thanks!

**Comment by rmmcclay** [comment]
Thanks @MrSorcus and allinurl for your comments and help.  I think my machine (CentOS 5) is too old.  I tried building from development, but git clone throws SSL errors, but then downloaded it from another server.  Then autoconf and autom4te errors. Compiled latest versions of those, but still not able to succeed.

**Comment by allinurl** [comment]
Are you able to try it on a more recent machine?

**Comment by rmmcclay** [comment]
Hi Geraldo - Yes indeed.  Successfully compiled and installed goaccess with GeoIP on a fresh AWS CentoOS machine yesterday.  goaccess rocks.

**Comment by allinurl** [comment]
@rmmcclay glad to hear it worked :) Closing this. Feel free to reopen it if needed.
