### ISSUE TITLE
Makefile:592: recipe for target 'src/geoip.o' failed

### ISSUE THREAD

**Issue by wil831** [allinurl/goaccess#869]
I'm trying to compile goaccess-1.2 and I'm getting this error after running the following on Ubuntu 16.04
> ./configure --enable-utf8 --enable-geoip=legacy
> make

> src/geoip.c: In function ‘geoip_free’:
> src/geoip.c:65:3: warning: implicit declaration of function ‘GeoIP_cleanup’ [-Wimplicit-function-dec    laration]
>    GeoIP_cleanup ();
>    ^
> src/geoip.c:65:3: warning: nested extern declaration of ‘GeoIP_cleanup’ [-Wnested-externs]
> src/geoip.c: In function ‘geoip_get_country_by_geoid’:
> src/geoip.c:226:15: warning: implicit declaration of function ‘GeoIP_country_name_by_name_v6’ [-Wimp    licit-function-declaration]
>      country = GeoIP_country_name_by_name_v6 (geo_location_data, addr);
>                ^
> src/geoip.c:226:5: warning: nested extern declaration of ‘GeoIP_country_name_by_name_v6’ [-Wnested-e    xterns]
>      country = GeoIP_country_name_by_name_v6 (geo_location_data, addr);
>      ^
> src/geoip.c:226:13: warning: assignment makes pointer from integer without a cast [-Wint-conversion]
>      country = GeoIP_country_name_by_name_v6 (geo_location_data, addr);
>              ^
> src/geoip.c: In function ‘geoip_get_country’:
> src/geoip.c:281:8: error: ‘GEOIP_CITY_EDITION_REV0_V6’ undeclared (first use in this function)
>    case GEOIP_CITY_EDITION_REV0_V6:
>         ^
> src/geoip.c:281:8: note: each undeclared identifier is reported only once for each function it appea    rs in
> src/geoip.c:282:8: error: ‘GEOIP_CITY_EDITION_REV1_V6’ undeclared (first use in this function)
>    case GEOIP_CITY_EDITION_REV1_V6:
>         ^
> src/geoip.c: In function ‘geoip_get_continent’:
> src/geoip.c:358:8: error: ‘GEOIP_CITY_EDITION_REV0_V6’ undeclared (first use in this function)
>    case GEOIP_CITY_EDITION_REV0_V6:
>         ^
> src/geoip.c:359:8: error: ‘GEOIP_CITY_EDITION_REV1_V6’ undeclared (first use in this function)
>    case GEOIP_CITY_EDITION_REV1_V6:
>         ^
> src/geoip.c: In function ‘geoip_get_city’:
> src/geoip.c:407:8: error: ‘GEOIP_CITY_EDITION_REV0_V6’ undeclared (first use in this function)
>    case GEOIP_CITY_EDITION_REV0_V6:
>         ^
> src/geoip.c:408:8: error: ‘GEOIP_CITY_EDITION_REV1_V6’ undeclared (first use in this function)
>    case GEOIP_CITY_EDITION_REV1_V6:
>         ^
> Makefile:592: recipe for target 'src/geoip.o' failed
> make[1]: *** [src/geoip.o] Error 1
> make[1]: Leaving directory '/home/bpmdb/goaccess-1.2'
> Makefile:359: recipe for target 'all' failed
> make: *** [all] Error 2

**Comment by allinurl** [comment]
I'm assuming you  installed `libgeoip-dev`, e.g.,

    $ sudo apt-get install libgeoip-dev

**Comment by wil831** [comment]
Yes. Although I was able to compile w/ mmdb instead.

> $ ./configure --prefix=/etc/goaccess --enable-utf8 --enable-geoip=mmdb

**Comment by allinurl** [comment]
Interesting, I'm guessing your distro must be packaging the libmaxminddb instead. Were you able to run goaccess then?

**Comment by wil831** [comment]
I actually manually installed libmaxminddb-dev since legacy wasn't working.  Yes, I can compile it with mmdb and I got it working. Just couldn't compile it with legacy GeoIP.

I also notice a couple errors when running ./configure:

> $ ./configure --enable-utf8 --enable-geoip=legacy
> checking for GeoIP_new in -lGeoIP... yes
> ./configure: line 4378: ,: command not found

> $ ./configure --enable-utf8 --enable-geoip=mmdb
> checking for MMDB_open in -lmaxminddb... yes
> ./configure: line 4324: ,: command not found

**Comment by allinurl** [comment]
Using a clean vanilla install of Ubuntu 16.04, I did `apt-get install libncursesw5-dev libgeoip-dev` and then ran:

    $ ./configure --enable-utf8 --enable-geoip=legacy
    $ make

and it built fine without any errors. However, did see the warning you posted above, so I pushed a fix that should address the syntax errors on configure, so please feel free to build again from [development](https://github.com/allinurl/goaccess#build-from-github-development) and let me know how it goes. Thanks.

**Comment by wil831** [comment]
I was able to build it on a new clean install of Ubuntu 16.04 on a test vmware as well.  I followed the guide for development and got this error on both test and production server:

> $ git clone https://github.com/allinurl/goaccess.git
> $ cd goaccess
> $ autoreconf -fiv
> $ ./configure --enable-utf8 --enable-geoip=legacy
> $ make
> 
> depbase=`echo src/bin2c.o | sed 's|[^/]*$|.deps/&|;s|\.o$||'`;\
> gcc -DLOCALEDIR=\"/usr/local/share/locale\" -DHAVE_CONFIG_H -I. -I./src    -O2 -DSYSCONFDIR=\"/usr/local/etc\" -Wno-long-long -Wall -W -Wnested-externs -Wformat=2 -Wmissing-prototypes -Wstrict-prototypes -Wmissing-declarations -Wwrite-strings -Wshadow -Wpointer-arith -Wsign-compare -Wbad-function-cast -Winline -Wcast-align -Wextra -Wdeclaration-after-statement -Wno-missing-field-initializers -pthread -MT src/bin2c.o -MD -MP -MF $depbase.Tpo -c -o src/bin2c.o src/bin2c.c &&\
> mv -f $depbase.Tpo $depbase.Po
> src/bin2c.c: In function ‘main’:
> src/bin2c.c:57:3: warning: ignoring return value of ‘fread’, declared with attribute warn_unused_result [-Wunused-result]
>    fread (buf, file_size, 1, f_input);
>    ^
> gcc -O2 -DSYSCONFDIR=\"/usr/local/etc\" -Wno-long-long -Wall -W -Wnested-externs -Wformat=2 -Wmissing-prototypes -Wstrict-prototypes -Wmissing-declarations -Wwrite-strings -Wshadow -Wpointer-arith -Wsign-compare -Wbad-function-cast -Winline -Wcast-align -Wextra -Wdeclaration-after-statement -Wno-missing-field-initializers -pthread -rdynamic  -o bin2c src/bin2c.o  -lnsl -lncursesw -lGeoIP -lpthread
> ./bin2c resources/tpls.html src/tpls.h tpls
> ./bin2c resources/css/bootstrap.min.css src/bootstrapcss.h bootstrap_css
> ./bin2c resources/css/fa.min.css src/facss.h fa_css
> ./bin2c resources/css/app.css src/appcss.h app_css
> ./bin2c resources/js/d3.v3.min.js src/d3js.h d3_js
> ./bin2c resources/js/hogan.min.js src/hoganjs.h hogan_js
> ./bin2c resources/js/charts.js src/chartsjs.h charts_js
> ./bin2c resources/js/app.js src/appjs.h app_js
> make  all-recursive
> make[1]: Entering directory '/home/bpmdb/test/goaccess'
> Making all in po
> make[2]: Entering directory '/home/bpmdb/test/goaccess/po'
> test ! -f ./goaccess.pot || \
>   test -z "fr.gmo es.gmo" || make fr.gmo es.gmo
> make[3]: Entering directory '/home/bpmdb/test/goaccess/po'
> : --update  --lang=fr fr.po goaccess.pot
> rm -f fr.gmo && : -c --statistics --verbose -o fr.gmo fr.po
> mv: cannot stat 't-fr.gmo': No such file or directory
> Makefile:169: recipe for target 'fr.gmo' failed
> make[3]: *** [fr.gmo] Error 1
> make[3]: Leaving directory '/home/bpmdb/test/goaccess/po'
> Makefile:206: recipe for target 'stamp-po' failed
> make[2]: *** [stamp-po] Error 2
> make[2]: Leaving directory '/home/bpmdb/test/goaccess/po'
> Makefile:798: recipe for target 'all-recursive' failed
> make[1]: *** [all-recursive] Error 1
> make[1]: Leaving directory '/home/bpmdb/test/goaccess'
> Makefile:506: recipe for target 'all' failed
> make: *** [all] Error 2
> 
> 
>

**Comment by wil831** [comment]
I'm able to build now on the new test server.  I'm using the Official GoAccess' Debian/Ubuntu Repository instead on the production server since I still get the same error from the original post.  Thanks

**Comment by allinurl** [comment]
Great, so did the commit I push fixed the original issue?

**Comment by wil831** [comment]
Yup thanks
